### ISSUE TITLE
Build number inconsistency

### ISSUE THREAD

**Issue by tellison** [rh-openjdk/marketplace#10]
Should you care, the build numbers are not present on the [Java 8 release names](https://github.com/rh-openjdk/marketplace/blob/fa164412dd09a1771a84691c9c7672d38aceb882/8/jdk8u332.json#L4), but they are on [Java 11 names](https://github.com/rh-openjdk/marketplace/blob/fa164412dd09a1771a84691c9c7672d38aceb882/11/jdk_11_0_15.json#L4) and [Java 17 names](https://github.com/rh-openjdk/marketplace/blob/fa164412dd09a1771a84691c9c7672d38aceb882/17/jdk_17_0_3.json#L4).

Not a problem for the marketplace, but just FYI in case it was an oversight.

**Comment by gnu-andrew** [comment]
Good catch. They should be consistent. I'll fix this when I'm back on Monday.
