### ISSUE TITLE
Marketplace data contains incorrect links

### ISSUE THREAD

**Issue by tellison** [rh-openjdk/marketplace#33]
There appears to be a bug in whatever is generating the marketplace data, as I spy a few links that are incorrect.

The one I spotted is [the link for the JDK 17.0.8 binary which actually points to the source archive](https://github.com/rh-openjdk/marketplace/blob/abbd369376e3cb06e5d1fb48dfc65437bd1ab7a6/17/jdk_17_0_8.json#L29), and that doesn't match [the sha256sum value](https://github.com/rh-openjdk/marketplace/blob/abbd369376e3cb06e5d1fb48dfc65437bd1ab7a6/17/jdk_17_0_8.json#L30C11-L30C11).

I have not done an extensive check in this file or other Java versions (and don't know where the code lives that generates this file).

The link to [AQAvit results for that binary](https://github.com/rh-openjdk/marketplace/blob/abbd369376e3cb06e5d1fb48dfc65437bd1ab7a6/17/jdk_17_0_8.json#L36) also points to the source files, which doesn't appear to contain any AQAvit results.

**Comment by gnu-andrew** [comment]
Ok, I'll have a look at this in more detail on Monday.

Incidentally, "whatever is generating the marketplace data" is me at present.  I'd like a more automated solution but the data I'm
consuming doesn't naturally lend itself to this. It's on my (long) todo list.

Should our commit tests	not catch things like this? I guess it's difficult to provide something that will work with all possible links
and be able to tell one tarball from another. Maybe it could do something as basic as checking a binary tarball includes `bin/java`?

**Comment by tellison** [comment]
> Should our commit tests not catch things like this?

Yes, it _should_. I thought you had created [the local PR verify tests](https://github.com/rh-openjdk/marketplace/blob/main/scripts/verify_marketplace_files.sh)? So you'll know what that covers.

> I guess it's difficult to provide something that will work with all possible links and be able to tell one tarball from another. Maybe it could do something as basic as checking a binary tarball includes `bin/java`?

The [Adoptium marketplace verification](https://github.com/adoptium/marketplace-data/blob/main/.github/workflows/validate-data.yml) will check the data meets the schema, and there was a [download test](https://github.com/adoptium/marketplace-data/blob/1d3f8e38836d5b536aeecffaea6ee22173859f51/.github/workflows/validate-data.yml#L62) that would have found this problem that [was disabled](https://github.com/adoptium/marketplace-data/pull/111) because it was failing.

Was that test possibly failing because the data was wrong?!

**Comment by gnu-andrew** [comment]
> > Should our commit tests not catch things like this?
> 
> Yes, it _should_. I thought you had created [the local PR verify tests](https://github.com/rh-openjdk/marketplace/blob/main/scripts/verify_marketplace_files.sh)? So you'll know what that covers.

I did. It's only a very basic sanity check of the files (check the JSON parses, check the signatures are valid). It doesn't interpret the data in the file in any way. It was a bit of a hack to even pull out the date and check it parses.

You could probably add a check to grab the links and check they are accessible, but pairing checksums with links and checking what is in the files requires more context than the script has.

I was thinking more of the Adoptium tests which I assumed did more checks on the content (otherwise why have the longer second check?)

> 
> > I guess it's difficult to provide something that will work with all possible links and be able to tell one tarball from another. Maybe it could do something as basic as checking a binary tarball includes `bin/java`?
> 
> The [Adoptium marketplace verification](https://github.com/adoptium/marketplace-data/blob/main/.github/workflows/validate-data.yml) will check the data meets the schema, and there was a [download test](https://github.com/adoptium/marketplace-data/blob/1d3f8e38836d5b536aeecffaea6ee22173859f51/.github/workflows/validate-data.yml#L62) that would have found this problem that [was disabled](https://github.com/adoptium/marketplace-data/pull/111) because it was failing.
> 

It looks like the download check does validate the checksums and would have caught the mismatch here. However, it doesn't verify the contents of the archives, so wouldn't catch a situation where the file matches its checksum, but the wrong file is being used (e.g. source zip given as GNU/Linux binary, GNU/Linux binary given as Windows binary, etc.)

> Was that test possibly failing because the data was wrong?!

Not as far as I know. I don't know all the reasons it was turned off, but it wasn't even finding the JSON file in our case:

~~~
Error: Unable to process file command 'output' successfully.
Error: Invalid format '11/jdk_11_0_20.json'
~~~

https://github.com/rh-openjdk/marketplace/actions/runs/5651133545/job/15308709075

**Comment by tellison** [comment]
> > > Should our commit tests not catch things like this?
> > 
> > 
> > Yes, it _should_. I thought you had created [the local PR verify tests](https://github.com/rh-openjdk/marketplace/blob/main/scripts/verify_marketplace_files.sh)? So you'll know what that covers.
> 
> I did. It's only a very basic sanity check of the files (check the JSON parses, check the signatures are valid). It doesn't interpret the data in the file in any way. It was a bit of a hack to even pull out the date and check it parses.
> 
> You could probably add a check to grab the links and check they are accessible, but pairing checksums with links and checking what is in the files requires more context than the script has.
> 
> I was thinking more of the Adoptium tests which I assumed did more checks on the content (otherwise why have the longer second check?)

The longer check in Adoptium is building the marketplace json schema and validating the incoming data against the latest definition, to advise that the data will be used. Where the marketplace reads invalid data it is ignored and the marketplace API (and thereby website) are not updated. So it is more than a valid json check.

The download check was intended to ensure that the links were reachable and matched the checksums. They don't validate that it is a good java.

> > > I guess it's difficult to provide something that will work with all possible links and be able to tell one tarball from another. Maybe it could do something as basic as checking a binary tarball includes `bin/java`?
> > 
> > 
> > The [Adoptium marketplace verification](https://github.com/adoptium/marketplace-data/blob/main/.github/workflows/validate-data.yml) will check the data meets the schema, and there was a [download test](https://github.com/adoptium/marketplace-data/blob/1d3f8e38836d5b536aeecffaea6ee22173859f51/.github/workflows/validate-data.yml#L62) that would have found this problem that [was disabled](https://github.com/adoptium/marketplace-data/pull/111) because it was failing.
> 
> It looks like the download check does validate the checksums and would have caught the mismatch here. However, it doesn't verify the contents of the archives, so wouldn't catch a situation where the file matches its checksum, but the wrong file is being used (e.g. source zip given as GNU/Linux binary, GNU/Linux binary given as Windows binary, etc.)

Understood. Ultimately the publisher is responsible for their data, Adoptium are just providing code that allow publishers (including Adoptium itself) to catch problems. Enhancing the sharable tests for sanity of the download content would make sense.

> > Was that test possibly failing because the data was wrong?!
> 
> Not as far as I know. I don't know all the reasons it was turned off, but it wasn't even finding the JSON file in our case:
> 
> ```
> Error: Unable to process file command 'output' successfully.
> Error: Invalid format '11/jdk_11_0_20.json'
> ```
> 
> https://github.com/rh-openjdk/marketplace/actions/runs/5651133545/job/15308709075
> 
> It failed on all three JDKs, not just the one with this issue (17u).

ACK - thanks.
